export const AUTHENTICATE = "AUTHENTICATE";
export const SIGN_OFF = "SIGN_OFF";
export const ADD_PROVIDER = "ADD_PROVIDER";
export const DELETE_PROVIDER = "DELETE_PROVIDER";
export const UPDATE_PROVIDER = "UPDATE_PROVIDER";

export const ADD_DASHBOARD = "ADD_DASHBOARD";

export const CHANGE_CURRENT_THEME = "CHANGE_CURRENT_THEME";
